version: "3"

services:
  nginx:
    build:
      context: ./docker-image/nginx
    image: news-nginx:1.11
    container_name: yii2-nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./runtime/nginx:/opt/log/nginx
      - ./:/opt/webroot
      - ./docker-image/nginx/config/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - php
    networks:
      - frontend
    ports:
      - "8181:8181"


  php:
    build:
      context: ./docker-image/php
    image: news-php:7
    container_name: yii2-php
    environment:
      - TZ=Asia/Shanghai
      - DBGP_IDEKEY=docker-php-debug
    volumes:
      - ./runtime/php:/opt/log/php
      - ./:/opt/webroot
    networks:
      - frontend
      - backend
    cap_add:
      - SYS_PTRACE
#  redis:
#    image: redis:3.0
#    container_name: news-redis
#    environment:
#      - TZ=Asia/Shanghai
#    command: "redis-server --requirepass just4redis"
#    volumes:
#      - ./runtime/redis-data:/data
#    ports:
#      - "127.0.0.1:6379:6379"
#    networks:
#      - backend


networks:
    frontend:
    backend:
